# Generated by Django 4.2.1 on 2023-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_services', models.CharField(max_length=50)),
                ('descriptions', models.TextField(max_length=200)),
                ('icon', models.CharField(choices=[('bi-briefcase', 'Briefcase'), ('bi-card-checklist', 'Card Checklist'), ('bi-bar-chart', 'Bar Chart'), ('bi-binoculars', 'Binoculars'), ('bi-brightness-high', 'High Brightness'), ('bi-calendar4-week', 'Calendar (4 weeks)')], max_length=30)),
            ],
        ),
    ]
